# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

# General config
AllCops:
  Enabled: true
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "config/**"
    - "config/**/**"
    - "bin/**"
    - "db/schema.rb"
    - "db/migrate/*"

# Specific cop configs
Style/FrozenStringLiteralComment:
  Exclude:
    - "app/views/**/**"

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 10
RSpec/IndexedLet:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails
